// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bifrost-di/example"
	"fmt"
)

// Injectors from wire.go:

func InitializeCar(pertalite example.Pertalite, body example.Body) example.Car {
	gas := example.Gas{
		GasOil: pertalite,
	}
	oil := example.Oil{}
	engine := example.Engine{
		Gas: gas,
		Oil: oil,
	}
	car := example.Car{
		Engine: engine,
		Body:   body,
	}
	return car
}

func InitializeEngine(pertalite example.Pertalite) example.Engine {
	gas := example.Gas{
		GasOil: pertalite,
	}
	oil := example.Oil{}
	engine := example.Engine{
		Gas: gas,
		Oil: oil,
	}
	return engine
}

// wire.go:

func init() {
	fmt.Println("Initializer")
}
