// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bifrost-di/example"
)

// Injectors from wire.go:

func InitializeCar(gas example.Pertalite, body example.Body) example.Car {
	exampleGas := example.Gas{
		GasOil: gas,
	}
	oil := example.Oil{}
	engine := example.Engine{
		Gas: exampleGas,
		Oil: oil,
	}
	car := example.Car{
		Engine: engine,
		Body:   body,
	}
	return car
}
